name: Canary (PR -> main)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

concurrency:
  group: canary-main-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  canary:
    name: Canary publish next
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Precisamos estar na branch do PR (não em detached HEAD) para o 'lerna version' poder commitar e taggear
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          fetch-tags: true
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
      - name: Git identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Setup npm auth
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          npm whoami || true
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build (optional)
        run: yarn build:libs
      - name: Test (optional)
        run: yarn test:run
      - name: Compute ephemeral canary version
        id: version
        run: |
          BASE_VERSION=$(node -p 'require("./lerna.json").version')
          SHORT_SHA=$(git rev-parse --short HEAD)
          EPHEMERAL_VERSION="${BASE_VERSION}-next.${SHORT_SHA}"
          echo "EPHEMERAL_VERSION=$EPHEMERAL_VERSION" >> $GITHUB_ENV
          echo "EPHEMERAL_VERSION=$EPHEMERAL_VERSION" >> $GITHUB_OUTPUT
      - name: Inject ephemeral version in packages
        run: |
          EPV="$EPHEMERAL_VERSION"
          echo "Aplicando versão efêmera $EPV nos package.json (sem commit)" 
          jq --arg v "$EPV" '.version = $v' lerna.json > lerna.tmp && mv lerna.tmp lerna.json
          for PKG in packages/*/package.json; do
            jq --arg v "$EPV" '.version = $v' "$PKG" > "$PKG.tmp" && mv "$PKG.tmp" "$PKG" || exit 1
          done
      - name: Publish canary (no commit/tag)
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # Publica todos os pacotes com a versão efêmera e dist-tag next sem criar git commit/tag
          npx lerna publish from-package --dist-tag next --yes --no-verify-access || echo "Nenhum pacote alterado para publicar (ok)"
          echo "CURRENT_VERSION=$EPHEMERAL_VERSION" >> $GITHUB_ENV
      - name: PR Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const curr = process.env.CURRENT_VERSION;
            const body = `Canary publicado (ephemeral): v${curr} (dist-tag next) - sem commit de versão`;
            if (!context.issue.number) {
              core.warning('Sem issue/PR number detectado para comentar.');
            } else {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body
              });
            }
