name: Minor Release (merge main -> latest)

on:
  pull_request:
    types: [closed]
    branches:
      - latest

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  minor:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'main'
    runs-on: ubuntu-latest
    name: Minor publish
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
      - name: Git identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          echo "GITHUB_TOKEN=${{ secrets.IQ_ADM_TIM_TOKEN }}" >> $GITHUB_ENV
      - name: Setup npm auth
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          npm whoami || true
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build libs
        run: yarn build:libs
      - name: Increment ephemeral version
        run: |
          npx lerna version minor --yes --no-push
      - name: Publish NPM
        run: yarn publish:from-package
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Revert ephemeral commit
        run: |
          git reset --hard HEAD~1
      - name: Define branch name
        id: define-branch
        run: echo "::set-output name=branch_name::update-minor-$(date +%s)"
      - name: Create branch and bump version
        run: |
          git checkout -b ${{ steps.define-branch.outputs.branch_name }}
          git push origin ${{ steps.define-branch.outputs.branch_name }}
          npx lerna version minor --yes --force-git-tag
      - name: Open PR to main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.define-branch.outputs.branch_name }}
          base: main
          title: "[skip] chore: bump minor version"
          body: |
            This PR bumps the minor version.
          commit-message: "chore: bump minor version"
        env:
          GITHUB_TOKEN: ${{ secrets.IQ_ADM_TIM_TOKEN }}
