name: Patch Release (merge -> main)

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  patch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Patch publish
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
      - name: Git identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Setup npm auth
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          npm whoami || true
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build libs
        run: yarn build:libs
      - name: Patch version & publish
        id: patch
        run: |
          yarn publish:patch
          VERSION=$(node -p 'require("./lerna.json").version')
          echo "CURRENT_VERSION=$VERSION" >> $GITHUB_ENV
          echo "PREVIOUS_TAG=$(git describe --tags --abbrev=0 --exclude $VERSION 2>/dev/null || echo '')" >> $GITHUB_ENV
      - name: PR Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prev = process.env.PREVIOUS_TAG;
            const curr = `v${process.env.CURRENT_VERSION}`;
            const diff = prev ? `\nDiff: https://github.com/${context.repo.owner}/${context.repo.repo}/compare/${prev}...${curr}` : '';
            const body = `Patch release publicado: ${curr}${diff}`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });
