name: Pre-release

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: write # for checkout and tag
  pull-requests: write # for comments
  packages: write # for publish

jobs:
  disabled:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo "Workflow legacy desativado. Use canary-main.yml / patch-release-main.yml / minor-release-latest.yml"
