name: release prod
on:
  # When Release Pull Request is merged
  pull_request:
    branches:
      - latest
    types: [closed]
  workflow_dispatch: {}

permissions:
  contents: write # for checkout and tag
  pull-requests: write # for comments
  packages: write # for publish

jobs:
  disabled:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo "Workflow legacy desativado. Use minor-release-latest.yml"
