
name: Jest test validators

on:
  pull_request:
    branches: [ main, latest ]

jobs:
  test:
    name: Test specific packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: install deps
        run: yarn install
      - name: build libs
        run: yarn build:libs
      - name: Check changed packages
        uses: dorny/paths-filter@v2
        id: changes
        with: 
          filters: |
            client:
              - 'packages/client/src/**'
            validators: 
              - 'packages/validators/src/**'
            clientCore:
              - 'packages/client-core/lib/**'

      - name: test client Core
        if: steps.changes.outputs.clientCore == 'true'
        uses: mattallty/jest-github-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "yarn test:client-core"

      - name: test client core (with client)
        if: steps.changes.outputs.clientCore == 'true'
        uses: mattallty/jest-github-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "yarn test:client"

      - name: test client
        if: steps.changes.outputs.client == 'true' 
        uses: mattallty/jest-github-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "yarn test:client"

      - name: test validators
        if: steps.changes.outputs.validators == 'true'
        uses: mattallty/jest-github-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "yarn test:validators"


