name: Jest test validators

on:
  pull_request:
    branches: [main, latest]

jobs:
  test:
    name: Test specific packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: install deps
        run: yarn install
      - name: build libs
        run: yarn build:libs
      - name: Check changed packages
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            client:
              - 'packages/client/src/**'
            validators:
              - 'packages/validators/src/**'
            clientCore:
              - 'packages/client-core/lib/**'

      # Executa sempre todos os testes (ifs removidos para diagnosticar branch protection)
      - name: test client core
        run: yarn test:client-core:coverage

      - name: Report Client Core Coverage
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: client-core
          json-summary-path: coverage/coverage-summary.json
          json-final-path: coverage/coverage-final.json

      - name: test client
        run: yarn test:client:coverage

      - name: Report Client Coverage
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: client
          json-summary-path: coverage/coverage-summary.json
          json-final-path: coverage/coverage-final.json

      - name: test validators
        run: yarn test:validators:coverage

      - name: Report Validators Coverage
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: validators
          json-summary-path: coverage/coverage-summary.json
          json-final-path: coverage/coverage-final.json
